### ISSUE TITLE
Migrate compressed files from lz4net

### ISSUE THREAD

**Issue by aschiffmann** [MiloszKrajewski/K4os.Compression.LZ4#20] opened 2019-04-25 12:27 UTC
We are updating our application from lz4net to K4os.Compression.LZ4 and are looking for a way to decompress old data compressed with lz4net (in stream mode) using K4os.Compression.LZ4.
However decompression always throws an `InvalidDataException` with the message "LZ4 frame magic number expected".

Compression in lz4net has been done by calling

    new LZ4Stream(fileStream, CompressionMode.Compress)

the code for decompression is

    LZ4Stream.Decode(fileStream)

Here is an example file which has been compressed with lz4net: [loremIpsum-lz4net.txt](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/files/3116785/loremIpsum-lz4net.txt)
Here is the same file uncompressed and compressed with K4os.Compression.LZ4: [loremIpsum-k4osLZ4.txt](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/files/3116784/loremIpsum-k4osLZ4.txt) [loremIpsum-uncompressed.txt](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/files/3116786/loremIpsum-uncompressed.txt)

Am I missing any settings which are necessary to decompress files which have been compressed with lz4net or is this not possible at all?

Thanks heaps :)

**Comment by MiloszKrajewski** [comment] 2019-04-25 13:45
This is not a bug but "missing feature". 

Few words of explanation: `lz4net` was NOT compatible with LZ4Frame format (https://github.com/MiloszKrajewski/lz4net/blob/master/doc/compatibility.md) and it was one of main complaints. When I was implementing `K4os.Compression.LZ4` it was a primary objective to have LZ4Frame streams and being backward compatible was not. 
I did acknowledge it though by putting: "add LegacyLz4Stream (compatible with lz4net, but not lz4 frame)" in "What's next..." issue (#5).

After this long into:
**I'm accepting it as priority issue, and I will release new package: `K4os.Compression.LZ4.Legacy`**

**Comment by MiloszKrajewski** [comment] 2019-04-28 20:35
Released as `K4os.Compressions.LZ4.Legacy` (separate assembly)

**Closed** 2019-04-29 08:43 UTC
Labels: enhancement
